from .groqchat import NODE_CLASS_MAPPINGS as GROQ_CLASS_MAPPINGS
from .groqchat import NODE_DISPLAY_NAME_MAPPINGS as GROQ_DISPLAY_MAPPINGS
from .PaliGemmaPixelProse import NODE_CLASS_MAPPINGS as PALI_CLASS_MAPPINGS
from .PaliGemmaPixelProse import NODE_DISPLAY_NAME_MAPPINGS as PALI_DISPLAY_MAPPINGS
from .moonshot_chat_nodes import NODE_CLASS_MAPPINGS as MOONSHOT_CLASS_MAPPINGS
from .moonshot_chat_nodes import NODE_DISPLAY_NAME_MAPPINGS as MOONSHOT_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**GROQ_CLASS_MAPPINGS, **PALI_CLASS_MAPPINGS, **MOONSHOT_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GROQ_DISPLAY_MAPPINGS, **PALI_DISPLAY_MAPPINGS, **MOONSHOT_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]